---
baseUrl: https://tmcfarlin412.github.io 
url: https://tmcfarlin412.github.io
plugins:
  - jekyll-feed 
future: false
defaults:
-
  scope:
      path: "" # an empty string here means all files in the project
  values:
    user: "tom"
... 
